In [ ]:
# Student Marks Analysis System
import numpy as np
stud=np.array(['Aditi','Saurab',"Gauri","Chaitanya","Ravi","Guru"])
sub=np.array(["English","Science","Maths","Computer","Hindi"])
marks=np.array([[89,98,90,32,54],[54,65,67,87,98],[74,78,53,85,87],[75,86,32,75,86],[43,75,87,97,34],[64,76,86,43,76]])
avg_marks=np.mean(marks,axis=0)
print(avg_marks)
highest=np.max(marks,axis=0)
lowest=np.min(marks,axis=0)
print(highest)
print(lowest)
std=np.std(marks,axis=0)
print(std)
rank=np.array([])
sort_idx=np.argsort(avg_marks) #returns the sorted indices
sort_idx=sort_idx[::-1]
for i in sort_idx:
  rank = np.append(rank, stud[i])
print(rank)
total_avg=np.mean(marks)
print(total_avg)
top_stud=stud[avg_marks>total_avg]
print(top_stud)



[72.6 74.2 75.4 70.8 67.2 69. ]
[98 98 87 86 97 86]
[32 54 53 32 34 43]
[25.3424545  15.96746692 12.14248739 20.0139951  24.6121921  14.75127113]
['Gauri' 'Saurab' 'Aditi' 'Chaitanya' 'Guru' 'Ravi']
71.53333333333333
['Aditi' 'Saurab' 'Gauri']


In [ ]:
# subject wise analysis
