In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=np.array([[[1,2],[2,3]],[[4,5],[6,7]]]) #3d
print(a)
print(type(a))
print(a.ndim)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]
<class 'numpy.ndarray'>
3


In [ ]:
zeros=np.zeros((2,3))
ones=np.ones((2,3))
np.full((2,3),7)
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linspace(0,1,5) #evenly spaced numbers in range 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# every numpy array has a single dtype as numpy array is homogeneous
a=np.arange(0,10,2)
print(a.dtype)
c=a.astype(np.float64) #used to convert into a particular dtype
print(c)

int64
[0. 2. 4. 6. 8.]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr=arr.reshape(3,2)
arr=arr.reshape(6,-1) #auto divide array elems into given rows equally
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
2
6
int64


In [43]:
arr1=np.array([[1,2],[3,4]])
arr=arr1.flatten() #return a copy
a=arr1.ravel() #returns view, shares memory with original array, faster than flatten, changes in array also modifies original
# but structure of original remains same
a[0]=99
print(arr1[0,1]) #2
print(arr1[0][1]) #2

2
2


In [ ]:
# universal functions
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a)
print(np.add(a,b))
# similarly subtract, divide, multiply, mod, power, abs works


[1 9 3 4]
[ 2 11  6  8]


In [3]:
a=np.array([1,2,3,4])
c=a[1:3]
c[0]=9
print(a)
# numpy slicing is based on references

[1 9 3 4]


In [ ]:
# fancy indexing - a way of indexing so that slicing takes a copy of array
a=np.array([1,2,3,4])
idx=[0,2]
b=a[idx]
b[0]=9
print(a)

[1 2 3 4]


In [ ]:
a=np.array([10,15,20,25,30])
print(a)
mask=a>18
print(mask)
print(a[mask])

[10 15 20 25 30]
[False False  True  True  True]
[20 25 30]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.stack((a,b),axis=0)) 

[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4 1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]]


In [ ]:
# append, insert, delete creates a copy of original
a=np.array([1,2,3])
print(np.append(a,[4,5]))
print(a)

[1 2 3 4 5]
[1 2 3]


In [62]:
# sort, unique also works on copy
a=np.array([3,1,4,1,1,5,9,2])
b=np.sort(a)
c=np.unique(a)
d=a[::-1]
print(a)
print(b)
print(c)
print(d)

[3 1 4 1 1 5 9 2]
[1 1 1 2 3 4 5 9]
[1 2 3 4 5 9]
[2 9 5 1 1 4 1 3]


In [ ]:
import numpy as np
# matrix
# transpose
a=np.array([[1,2],[3,4]])
a.T
# or
a.transpose()


[[1 2]
 [3 4]]


In [10]:
# matrix multiplication
v1=np.array([[1,2],[3,4]])
v2=np.array([[4],[5]])
np.dot(v1,v2)
# or
v1@v2

array([[14],
       [32]])

In [ ]:
# random
rng=np.random.default_rng(seed=42) #obj creation
rng.integers(1,50,size=(3,4))

Generator(PCG64)


array([[ 5, 38, 33, 22],
       [22, 43,  5, 35],
       [10,  5, 26, 48]])

In [18]:
rng.normal(loc=0,scale=1,size=5)

array([ 0.1278404 , -0.31624259, -0.01680116, -0.85304393,  0.87939797])

In [21]:
options=np.array(['a','b','c'])
rng.choice(options,size=2)

array(['b', 'c'], dtype='<U1')

In [27]:
rng.uniform(0,4,size=2)

array([3.11353399, 0.77855483])